# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with mkdocs 
formats:
  - pdf
  - htmlzip

sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: false

python:
  version: 3.8
  install:
    - requirements: source/requirements.txt