site_name: SCAR GeoMAP Documentation
nav:
    - Home: 'index.md'
    - Geology Glossary: 'field_glossary.md'
    - Chronostratigraphic Legend: 'legend.md'
theme: 
    name: readthedocs
    features:
        - navigation.tabs
markdown_extensions:
    - toc: 
        permalink: true
        toc_depth: 6
    - fenced_code
plugins:
    - search