site_name: SCAR GeoMAP Documentation
nav:
    - Home: 'index.md'
    - Geology Glossary: 'field_glossary.md'
    - Culture Glossary: 'culture_glossary.md'
theme: 
    name: readthedocs
    navigation_depth: 4
    features:
        - navigation.tabs
markdown_extensions:
    - toc: 
        permalink: true
        toc_depth: 3
    
