site_name: SCAR GeoMAP Documentation
nav:
    - Home: 'index.md'
    - Geology Glossary: 'field_glossary.md'
theme: 
    name: readthedocs
    navigation_depth: 4
markdown_extensions:
    - toc: 
        permalink: true
    
